server:
  port: 10002
spring:
  application:
    name: explore
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/,file:D:/apple
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 1000MB
      enabled: true
  datasource:
    url: jdbc:mysql://47.96.88.206:3306/jxkj?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: shj123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  cache:
    type: REDIS
    cache-names: redis_cache , ehcache
    redis:
      time-to-live: 60000
  redis:
    database: 0
    host: 47.96.88.206
    port: 6378
    password: shj@321
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    shutdown-timeout: 100ms
  data:
    mongodb:
      host: anoax.com
      port: 27017
      database: anoax_database
      username: anoax
      password: zhangan28
      repositories: true

security:
  oauth2:
    resource:
      jwt:
        key-value: auth.turbidexplore.com
com:
  turbid:
    upload-path:
      images: /home/alex/images/
    #腾讯云存储服务
    tencentoss:
      qcloud_file_accesskey: AKIDe5JJ4ZDaKo35vV7Ilz74rRr2hMnyReQx
      qcloud_file_secretkey: RLE4f0A5mDOiqkOozuaI0XqujKflYI0U
      #上海存储区
      qcloud_file_region: ap-chengdu
      #正式环境的桶 1
      qcloud_file_bucket: anoax-1258088094
    sms:
      appid: 1400284009
      appkey: 39932b40c6bbdad0ca10da22888660b0
      smsSign: 浑浊探索
